# Russian message translation file for plpython
# Copyright (C) 2012 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Alexander Lakhin <exclusion@gmail.com>, 2012.
#
# ChangeLog:
#
#   - April 3, 2012: Bug fixes. Alexander Lakhin <exclusion@gmail.com>.
#   - February 18, 2012: Complete translation for 9.1. Alexander Lakhin <exclusion@gmail.com>.
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 9.0\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2012-08-06 12:01+0000\n"
"PO-Revision-Date: 2012-08-06 17:20+0400\n"
"Last-Translator: Alexander Lakhin <exclusion@gmail.com>\n"
"Language-Team: Russian <pgtranslation-translators@pgfoundry.org>\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
"X-Generator: Lokalize 1.4\n"

#: plpython.c:418
#, c-format
msgid "PL/Python function \"%s\""
msgstr "функция PL/Python \"%s\""

#: plpython.c:425
msgid "PL/Python anonymous code block"
msgstr "анонимный блок кода PL/Python"

#: plpython.c:432
msgid "while modifying trigger row"
msgstr "при изменении строки в триггере"

#: plpython.c:439
msgid "while creating return value"
msgstr "при создании возвращаемого значения"

#: plpython.c:608 plpython.c:634
msgid "unexpected return value from trigger procedure"
msgstr "триггерная процедура вернула недопустимое значение"

#: plpython.c:609
msgid "Expected None or a string."
msgstr "Ожидалось None или строка."

#: plpython.c:624
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"триггерная функция PL/Python вернула \"MODIFY\" в триггере DELETE -- "
"игнорируется"

#: plpython.c:635
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Ожидалось None, \"OK\", \"SKIP\" или \"MODIFY\"."

#: plpython.c:687
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "элемент TD[\"new\"] удалён -- изменить строку нельзя"

#: plpython.c:690
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] - не словарь"

#: plpython.c:714
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "ключ словаря TD[\"new\"] с порядковым номером %d не является строкой"

#: plpython.c:720
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"ключу \"%s\", найденному в TD[\"new\"], не соответствует колонка в строке, "
"обрабатываемой триггером"

#: plpython.c:816
msgid "could not create new dictionary while building trigger arguments"
msgstr "не удалось создать словарь для передачи аргументов триггера"

#: plpython.c:1022
msgid "unsupported set function return mode"
msgstr "неподдерживаемый режим возврата для функции с результатом-множеством"

#: plpython.c:1023
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""
"Функции PL/Python с результатом-множеством могут возвращать только по одному "
"значению за вызов."

#: plpython.c:1035
msgid "returned object cannot be iterated"
msgstr "возвращаемый объект не поддерживает итерации"

#: plpython.c:1036
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"Функции PL/Python с результатом-множеством должны возвращать объекты с "
"возможностью итерации."

#: plpython.c:1063
msgid "error fetching next item from iterator"
msgstr "ошибка получения следующего элемента из итератора"

#: plpython.c:1098
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "функция PL/Python с типом результата \"void\" вернула не None"

#: plpython.c:1253
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "ошибка в PyList_SetItem() при настройке аргументов"

#: plpython.c:1257
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "ошибка в PyDict_SetItemString() при настройке аргументов"

#: plpython.c:1326
msgid "PyCObject_AsVoidPtr() failed"
msgstr "ошибка в PyCObject_AsVoidPtr()"

#: plpython.c:1434
msgid "trigger functions can only be called as triggers"
msgstr "триггерные функции могут вызываться только в триггерах"

#: plpython.c:1438 plpython.c:1822
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "функции PL/Python не могут возвращать тип %s"

#: plpython.c:1516
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "функции PL/Python не могут принимать тип %s"

#: plpython.c:1555
msgid "PyCObject_FromVoidPtr() failed"
msgstr "ошибка в PyCObject_FromVoidPtr()"

#: plpython.c:1613
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "не удалось скомпилировать функцию PL/Python \"%s\""

#: plpython.c:1824
msgid "PL/Python does not support conversion to arrays of row types."
msgstr "PL/Python не поддерживает преобразование в массивы кортежей."

#: plpython.c:2027
msgid "cannot convert multidimensional array to Python list"
msgstr "преобразовать многомерный массив в список Python нельзя"

#: plpython.c:2028
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python поддерживает только одномерные массивы."

#: plpython.c:2067
msgid "could not create new dictionary"
msgstr "не удалось создать словарь"

#: plpython.c:2139
msgid "could not create bytes representation of Python object"
msgstr "не удалось создать байтовое представление объекта Python"

#: plpython.c:2193
msgid "could not create string representation of Python object"
msgstr "не удалось создать строковое представление объекта Python"

#: plpython.c:2204
msgid ""
"could not convert Python object into cstring: Python string representation "
"appears to contain null bytes"
msgstr ""
"не удалось преобразовать объект Python в cstring: похоже, представление "
"строки Python содержит нулевые байты"

#: plpython.c:2238
msgid ""
"return value of function with array return type is not a Python sequence"
msgstr ""
"возвращаемое значение функции с результатом-массивом не является "
"последовательностью"

#: plpython.c:2313
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "ключ \"%s\" не найден в сопоставлении"

#: plpython.c:2314
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"Чтобы присвоить колонке NULL, добавьте в сопоставление значение None с "
"ключом-именем колонки."

#: plpython.c:2357
msgid "length of returned sequence did not match number of columns in row"
msgstr "длина возвращённой последовательности не равна числу колонок в строке"

#: plpython.c:2450
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "в объекте Python не существует атрибут \"%s\""

#: plpython.c:2451
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"Чтобы присвоить колонке NULL, присвойте возвращаемому значению атрибут с "
"именем колонки и значением None."

#: plpython.c:2685
msgid "plan.status takes no arguments"
msgstr "plan.status не принимает аргументы"

#: plpython.c:2804 plpython.c:2947
msgid "transaction aborted"
msgstr "транзакция прервана"

#: plpython.c:2811
msgid "invalid arguments for plpy.prepare"
msgstr "неверные аргументы plpy.prepare"

#: plpython.c:2818
msgid "second argument of plpy.prepare must be a sequence"
msgstr "вторым аргументом plpy.prepare должна быть последовательность"

#: plpython.c:2868
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: имя типа с порядковым номером %d не является строкой"

#: plpython.c:2895
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare не поддерживает составные типы"

#: plpython.c:2924
msgid "unrecognized error in PLy_spi_prepare"
msgstr "нераспознанная ошибка в PLy_spi_prepare"

#: plpython.c:2960
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute ожидает запрос или план"

#: plpython.c:2977
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute принимает в качестве второго аргумента последовательность"

#: plpython.c:2993
msgid "could not execute plan"
msgstr "нельзя выполнить план"

#: plpython.c:2996
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Ожидалась последовательность из %d аргумента, получено %d: %s"
msgstr[1] "Ожидалась последовательность из %d аргументов, получено %d: %s"
msgstr[2] "Ожидалась последовательность из %d аргументов, получено %d: %s"

#: plpython.c:3075
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr "нераспознанная ошибка в PLy_spi_execute_plan"

#: plpython.c:3094
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "ошибка в SPI_execute_plan: %s"

#: plpython.c:3121
msgid "unrecognized error in PLy_spi_execute_query"
msgstr "нераспознанная ошибка в PLy_spi_execute_query"

#: plpython.c:3130
#, c-format
msgid "SPI_execute failed: %s"
msgstr "ошибка в SPI_execute: %s"

#: plpython.c:3187
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "нераспознанная ошибка в PLy_spi_execute_fetch_result"

#: plpython.c:3247
msgid "Python major version mismatch in session"
msgstr "несовпадение базовой версии Python в сеансе"

#: plpython.c:3248
#, c-format
msgid ""
"This session has previously used Python major version %d, and it is now "
"attempting to use Python major version %d."
msgstr ""
"В данном сеансе до этого использовался Python базовой версии %d, а сейчас "
"планируется использовать Python версии %d."

#: plpython.c:3250
msgid "Start a new session to use a different Python major version."
msgstr ""
"Чтобы переключиться на другую базовую версию Python, начните новый сеанс."

#: plpython.c:3265
msgid "untrapped error in initialization"
msgstr "необработанная ошибка при инициализации"

#: plpython.c:3268
msgid "could not create procedure cache"
msgstr "не удалось создать процедурный кэш"

#: plpython.c:3280
msgid "could not import \"__main__\" module"
msgstr "не удалось импортировать модуль \"__main__\""

#: plpython.c:3287
msgid "could not initialize globals"
msgstr "не удалось инициализировать глобальные данные"

#: plpython.c:3405
msgid "could not parse error message in plpy.elog"
msgstr "не удалось разобрать сообщение об ошибке в plpy.elog"

#: plpython.c:3534 plpython.c:3538
#, c-format
msgid "PL/Python: %s"
msgstr "PL/Python: %s"

#: plpython.c:3535
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3648
msgid "out of memory"
msgstr "нехватка памяти"

#: plpython.c:3695
msgid "could not convert Python Unicode object to bytes"
msgstr "не удалось преобразовать объект Python Unicode в байты"

#: plpython.c:3700
msgid "could not extract bytes from encoded string"
msgstr "не удалось извлечь байты из кодированной строки"
